import { CommandNode, FlagSpec, ToolSchema } from "../types";

function sharedSearchFlags(): FlagSpec[] {
	return [
		{ flag: "--image", type: "path", label: "Search by image", description: "Use instead of the text query" },
		{ flag: "--collection", type: "string", label: "Collection" },
		{ flag: "--after", type: "date", label: "After date (YYYY-MM-DD)" },
		{ flag: "--before", type: "date", label: "Before date (YYYY-MM-DD)" },
		{ flag: "-n", type: "number", label: "Result limit" },
	];
}

const commands: CommandNode[] = [
	{
		id: "collection.add",
		argvPath: ["collection", "add"],
		category: "infra",
		label: "Collection → Add",
		positionals: [{ name: "path", type: "path", label: "Path", required: true }],
		flags: [
			{ flag: "--name", type: "string", label: "Collection name", required: true },
			{ flag: "--mask", type: "string", label: "Glob pattern", default: "**/*.{png,jpg,jpeg,webp,heic,gif}" },
			{ flag: "--sidecar-notes", type: "path", label: "Sidecar notes folder" },
			{ flag: "--sidecar-field", type: "string", label: "Sidecar frontmatter field", default: "ImageText" },
		],
		executionMode: "buffered",
	},
	{
		id: "collection.list",
		argvPath: ["collection", "list"],
		category: "infra",
		label: "Collection → List",
		positionals: [],
		flags: [],
		executionMode: "buffered",
	},
	{
		id: "collection.remove",
		argvPath: ["collection", "remove"],
		category: "infra",
		label: "Collection → Remove",
		positionals: [{ name: "name", type: "string", label: "Collection name", required: true }],
		flags: [],
		executionMode: "buffered",
		destructive: true,
	},
	{
		id: "collection.rename",
		argvPath: ["collection", "rename"],
		category: "infra",
		label: "Collection → Rename",
		positionals: [
			{ name: "oldName", type: "string", label: "Current name", required: true },
			{ name: "newName", type: "string", label: "New name", required: true },
		],
		flags: [],
		executionMode: "buffered",
	},
	{
		id: "ls",
		argvPath: ["ls"],
		category: "infra",
		label: "List indexed images",
		positionals: [{ name: "collection", type: "string", label: "Collection", required: false }],
		flags: [],
		executionMode: "buffered",
	},
	{
		id: "index",
		argvPath: ["index"],
		category: "infra",
		label: "Index (scan + extract EXIF/captions)",
		positionals: [],
		flags: [{ flag: "--collection", type: "string", label: "Collection" }],
		executionMode: "streaming",
	},
	{
		id: "embed",
		argvPath: ["embed"],
		category: "infra",
		label: "Generate embeddings (SigLIP 2)",
		positionals: [],
		flags: [
			{ flag: "--collection", type: "string", label: "Collection" },
			{ flag: "--force", type: "boolean", label: "Force re-embed" },
		],
		executionMode: "streaming",
	},
	{
		id: "caption",
		argvPath: ["caption"],
		category: "infra",
		label: "Generate AI captions (BLIP)",
		positionals: [],
		flags: [
			{ flag: "--collection", type: "string", label: "Collection" },
			{ flag: "--force", type: "boolean", label: "Force overwrite (never overwrites human captions otherwise)" },
		],
		executionMode: "streaming",
	},
	{
		id: "ocr",
		argvPath: ["ocr"],
		category: "infra",
		label: "Extract text via OCR",
		description: "Present in the qimg CLI but not documented in its README.",
		positionals: [],
		flags: [
			{ flag: "--collection", type: "string", label: "Collection" },
			{ flag: "--force", type: "boolean", label: "Force re-OCR" },
		],
		executionMode: "streaming",
	},
	{
		id: "tsearch",
		argvPath: ["tsearch"],
		category: "search",
		label: "Keyword search (tsearch)",
		positionals: [{ name: "query", type: "string", label: "Query", required: false }],
		flags: sharedSearchFlags(),
		executionMode: "buffered",
		jsonFlag: "--json",
	},
	{
		id: "vsearch",
		argvPath: ["vsearch"],
		category: "search",
		label: "Vector / image-similarity search (vsearch)",
		positionals: [{ name: "query", type: "string", label: "Query", required: false }],
		flags: sharedSearchFlags(),
		executionMode: "buffered",
		jsonFlag: "--json",
	},
	{
		id: "hsearch",
		argvPath: ["hsearch"],
		category: "search",
		label: "Hybrid search (hsearch)",
		positionals: [{ name: "query", type: "string", label: "Query", required: false }],
		flags: sharedSearchFlags(),
		executionMode: "buffered",
		jsonFlag: "--json",
	},
	{
		id: "get",
		argvPath: ["get"],
		category: "search",
		label: "Get image metadata",
		positionals: [{ name: "target", type: "string", label: "Path or #docid", required: true }],
		flags: [],
		executionMode: "buffered",
	},
	{
		id: "status",
		argvPath: ["status"],
		category: "infra",
		label: "Status",
		positionals: [],
		flags: [],
		executionMode: "buffered",
	},
];

export const qimgSchema: ToolSchema = { id: "qimg", commands };
