import { CommandNode, FlagSpec, ToolSchema } from "../types";

/** Flags shared by the four search commands (tsearch/vsearch/hsearch/fsearch). */
function sharedSearchFlags(): FlagSpec[] {
	return [
		{ flag: "-n", type: "number", label: "Result limit" },
		{
			flag: "-c",
			type: "string",
			label: "Collection",
			description: "Restrict to a collection (repeatable)",
			repeatable: true,
		},
		{ flag: "--all", type: "boolean", label: "Search all collections" },
		{ flag: "--min-score", type: "number", label: "Minimum score" },
		{ flag: "--full", type: "boolean", label: "Full document content" },
		{ flag: "--explain", type: "boolean", label: "Explain ranking" },
		{ flag: "--no-rerank", type: "boolean", label: "Disable reranking" },
		{ flag: "-C", type: "number", label: "Candidate limit", description: "--candidate-limit" },
		{ flag: "--intent", type: "string", label: "Intent hint" },
		{ flag: "--line-numbers", type: "boolean", label: "Show line numbers" },
		{ flag: "--csv", type: "boolean", label: "CSV output" },
		{ flag: "--md", type: "boolean", label: "Markdown output" },
		{ flag: "--xml", type: "boolean", label: "XML output" },
		{ flag: "--files", type: "boolean", label: "File list output" },
	];
}

const commands: CommandNode[] = [
	{
		id: "collection.add",
		argvPath: ["collection", "add"],
		category: "infra",
		label: "Collection → Add",
		positionals: [{ name: "path", type: "path", label: "Path", required: true }],
		flags: [
			{ flag: "--name", type: "string", label: "Collection name", required: true },
			{ flag: "--mask", type: "string", label: "Glob pattern", default: "**/*.md" },
			{ flag: "--heading-name", type: "string", label: "Heading name (scope to subsection)" },
			{ flag: "--heading-level", type: "number", label: "Heading level" },
		],
		executionMode: "buffered",
	},
	{
		id: "collection.list",
		argvPath: ["collection", "list"],
		category: "infra",
		label: "Collection → List",
		positionals: [],
		flags: [],
		executionMode: "buffered",
	},
	{
		id: "collection.show",
		argvPath: ["collection", "show"],
		category: "infra",
		label: "Collection → Show",
		positionals: [{ name: "name", type: "string", label: "Collection name", required: true }],
		flags: [],
		executionMode: "buffered",
	},
	{
		id: "collection.remove",
		argvPath: ["collection", "remove"],
		category: "infra",
		label: "Collection → Remove",
		positionals: [{ name: "name", type: "string", label: "Collection name", required: true }],
		flags: [],
		executionMode: "buffered",
		destructive: true,
	},
	{
		id: "collection.rename",
		argvPath: ["collection", "rename"],
		category: "infra",
		label: "Collection → Rename",
		positionals: [
			{ name: "oldName", type: "string", label: "Current name", required: true },
			{ name: "newName", type: "string", label: "New name", required: true },
		],
		flags: [],
		executionMode: "buffered",
	},
	{
		id: "collection.update-cmd",
		argvPath: ["collection", "update-cmd"],
		category: "infra",
		label: "Collection → Set update command",
		description: "Pre-index shell command (e.g. git pull). Omit to clear.",
		positionals: [
			{ name: "name", type: "string", label: "Collection name", required: true },
			{ name: "cmd", type: "string", label: "Update command", required: false },
		],
		flags: [],
		executionMode: "buffered",
	},
	{
		id: "collection.include",
		argvPath: ["collection", "include"],
		category: "infra",
		label: "Collection → Include in default search",
		positionals: [{ name: "name", type: "string", label: "Collection name", required: true }],
		flags: [],
		executionMode: "buffered",
	},
	{
		id: "collection.exclude",
		argvPath: ["collection", "exclude"],
		category: "infra",
		label: "Collection → Exclude from default search",
		positionals: [{ name: "name", type: "string", label: "Collection name", required: true }],
		flags: [],
		executionMode: "buffered",
	},
	{
		id: "ls",
		argvPath: ["ls"],
		category: "infra",
		label: "List files in a collection",
		positionals: [
			{ name: "target", type: "string", label: "Collection[/subpath]", required: true },
		],
		flags: [],
		executionMode: "buffered",
	},
	{
		id: "context.add",
		argvPath: ["context", "add"],
		category: "infra",
		label: "Context → Add",
		description: "Attach descriptive context to a collection/subfolder/global path.",
		positionals: [
			{ name: "path", type: "string", label: "Path (qmd:// or /)", required: false },
			{ name: "text", type: "string", label: "Context text", required: true },
		],
		flags: [],
		executionMode: "buffered",
	},
	{
		id: "context.list",
		argvPath: ["context", "list"],
		category: "infra",
		label: "Context → List",
		positionals: [],
		flags: [],
		executionMode: "buffered",
	},
	{
		id: "context.rm",
		argvPath: ["context", "rm"],
		category: "infra",
		label: "Context → Remove",
		positionals: [{ name: "path", type: "string", label: "Path", required: true }],
		flags: [],
		executionMode: "buffered",
		destructive: true,
	},
	{
		id: "index",
		argvPath: ["index"],
		category: "infra",
		label: "Index (rescan collections)",
		positionals: [],
		flags: [{ flag: "--pull", type: "boolean", label: "Run each collection's update-cmd first" }],
		executionMode: "streaming",
	},
	{
		id: "embed",
		argvPath: ["embed"],
		category: "infra",
		label: "Generate embeddings",
		positionals: [],
		flags: [
			{ flag: "-f", type: "boolean", label: "Force re-embed" },
			{
				flag: "--chunk-strategy",
				type: "enum",
				label: "Chunk strategy",
				enumValues: ["auto"],
			},
			{ flag: "--max-docs-per-batch", type: "number", label: "Max docs per batch" },
			{ flag: "--max-batch-mb", type: "number", label: "Max batch size (MB)" },
		],
		executionMode: "streaming",
	},
	{
		id: "pull",
		argvPath: ["pull"],
		category: "infra",
		label: "Pull models",
		description: "Pre-download/verify the embedding, reranker, and query-expansion models.",
		positionals: [],
		flags: [{ flag: "--refresh", type: "boolean", label: "Force re-download" }],
		executionMode: "streaming",
	},
	{
		id: "status",
		argvPath: ["status"],
		category: "infra",
		label: "Status",
		positionals: [],
		flags: [],
		executionMode: "buffered",
	},
	{
		id: "cleanup",
		argvPath: ["cleanup"],
		category: "infra",
		label: "Cleanup",
		description: "Clear LLM cache, remove orphaned vectors/inactive docs, vacuum DB.",
		positionals: [],
		flags: [],
		executionMode: "streaming",
		destructive: true,
	},
	{
		id: "tsearch",
		argvPath: ["tsearch"],
		category: "search",
		label: "Keyword search (tsearch)",
		positionals: [{ name: "query", type: "string", label: "Query", required: true }],
		flags: sharedSearchFlags(),
		executionMode: "buffered",
		jsonFlag: "--json",
	},
	{
		id: "vsearch",
		argvPath: ["vsearch"],
		category: "search",
		label: "Vector search (vsearch)",
		positionals: [{ name: "query", type: "string", label: "Query", required: true }],
		flags: sharedSearchFlags().map((f) => (f.flag === "--min-score" ? { ...f, default: 0.3 } : f)),
		executionMode: "buffered",
		jsonFlag: "--json",
	},
	{
		id: "hsearch",
		argvPath: ["hsearch"],
		category: "search",
		label: "Hybrid search (hsearch)",
		description: "Query expansion → BM25+vector → RRF fusion → LLM rerank.",
		positionals: [{ name: "query", type: "string", label: "Query", required: true }],
		flags: sharedSearchFlags(),
		executionMode: "buffered",
		jsonFlag: "--json",
	},
	{
		id: "fsearch",
		argvPath: ["fsearch"],
		category: "search",
		label: "Filter search (fsearch)",
		description: "Structured metadata/frontmatter filter DSL (no LLM).",
		positionals: [{ name: "filter", type: "string", label: "Filter DSL", required: true }],
		flags: sharedSearchFlags(),
		executionMode: "buffered",
		jsonFlag: "--json",
	},
	{
		id: "get",
		argvPath: ["get"],
		category: "search",
		label: "Get document",
		positionals: [{ name: "target", type: "string", label: "Path or #docid", required: true }],
		flags: [
			{ flag: "--section", type: "string", label: "Section heading (e.g. Heading/Sub)" },
			{ flag: "--no-callouts", type: "boolean", label: "Strip callouts" },
			{ flag: "--no-codeblocks", type: "boolean", label: "Strip code blocks" },
			{ flag: "--from", type: "number", label: "Start line" },
			{ flag: "-l", type: "number", label: "Line count" },
			{ flag: "--line-numbers", type: "boolean", label: "Show line numbers" },
		],
		executionMode: "buffered",
	},
	{
		id: "multi-get",
		argvPath: ["multi-get"],
		category: "search",
		label: "Get multiple documents",
		positionals: [{ name: "pattern", type: "string", label: "Glob or comma list", required: true }],
		flags: [
			{ flag: "--max-bytes", type: "number", label: "Max bytes per doc" },
			{ flag: "-l", type: "number", label: "Line count" },
		],
		executionMode: "buffered",
		jsonFlag: "--json",
	},
	{
		id: "bench",
		argvPath: ["bench"],
		category: "infra",
		label: "Run benchmark",
		positionals: [{ name: "fixture", type: "path", label: "Fixture JSON path", required: true }],
		flags: [{ flag: "-c", type: "string", label: "Collection", repeatable: true }],
		executionMode: "streaming",
		jsonFlag: "--json",
	},
	{
		id: "skill.show",
		argvPath: ["skill", "show"],
		category: "infra",
		label: "Skill → Show",
		positionals: [],
		flags: [],
		executionMode: "buffered",
	},
	{
		id: "skill.install",
		argvPath: ["skill", "install"],
		category: "infra",
		label: "Skill → Install",
		positionals: [],
		flags: [
			{ flag: "--global", type: "boolean", label: "Install globally" },
			{ flag: "--yes", type: "boolean", label: "Skip confirmation" },
			{ flag: "-f", type: "boolean", label: "Force overwrite" },
		],
		executionMode: "buffered",
	},
];

export const qmdSchema: ToolSchema = { id: "qmd", commands };
