import { CommandNode, ToolSchema } from "../types";

const FIELD_ENUM = ["up-frontmatter", "down-frontmatter", "right-inline", "left-inline", "in-inline", "out-inline"];

const commands: CommandNode[] = [
	{
		id: "collection.add",
		argvPath: ["collection", "add"],
		category: "infra",
		label: "Collection → Add",
		positionals: [{ name: "path", type: "path", label: "Path", required: true }],
		flags: [
			{ flag: "--name", type: "string", label: "Collection name", required: true },
			{ flag: "--pattern", type: "string", label: "Glob pattern", default: "**/*.md" },
			{ flag: "--ignore", type: "string", label: "Ignore globs (comma-separated)", repeatable: true },
			{ flag: "--vault-root", type: "path", label: "Vault root (for cross-folder wikilinks)" },
		],
		executionMode: "buffered",
	},
	{
		id: "collection.list",
		argvPath: ["collection", "list"],
		category: "infra",
		label: "Collection → List",
		positionals: [],
		flags: [],
		executionMode: "buffered",
	},
	{
		id: "collection.remove",
		argvPath: ["collection", "remove"],
		category: "infra",
		label: "Collection → Remove",
		positionals: [{ name: "name", type: "string", label: "Collection name", required: true }],
		flags: [],
		executionMode: "buffered",
		destructive: true,
	},
	{
		id: "collection.rename",
		argvPath: ["collection", "rename"],
		category: "infra",
		label: "Collection → Rename",
		positionals: [
			{ name: "oldName", type: "string", label: "Current name", required: true },
			{ name: "newName", type: "string", label: "New name", required: true },
		],
		flags: [],
		executionMode: "buffered",
	},
	{
		id: "fields.get",
		argvPath: ["fields", "get"],
		category: "infra",
		label: "Fields → Get mapping",
		positionals: [],
		flags: [{ flag: "--collection", type: "string", label: "Collection" }],
		executionMode: "buffered",
	},
	{
		id: "fields.set",
		argvPath: ["fields", "set"],
		category: "infra",
		label: "Fields → Set mapping",
		positionals: [
			{ name: "field", type: "enum", label: "Field", required: true, enumValues: FIELD_ENUM },
			{ name: "values", type: "string", label: "Frontmatter/inline keys (comma-separated)", required: true },
		],
		flags: [{ flag: "--collection", type: "string", label: "Collection" }],
		executionMode: "buffered",
	},
	{
		id: "fields.reset",
		argvPath: ["fields", "reset"],
		category: "infra",
		label: "Fields → Reset to defaults",
		positionals: [],
		flags: [{ flag: "--collection", type: "string", label: "Collection" }],
		executionMode: "buffered",
	},
	{
		id: "index",
		argvPath: ["index"],
		category: "infra",
		label: "Index (build/refresh graph)",
		positionals: [],
		flags: [
			{ flag: "--collection", type: "string", label: "Collection" },
			{ flag: "--force", type: "boolean", label: "Force full rebuild" },
		],
		executionMode: "streaming",
	},
	{
		id: "status",
		argvPath: ["status"],
		category: "infra",
		label: "Status",
		positionals: [],
		flags: [{ flag: "--collection", type: "string", label: "Collection" }],
		executionMode: "buffered",
	},
	{
		id: "get",
		argvPath: ["get"],
		category: "search",
		label: "Get node",
		description: "All incoming/outgoing edges and metrics for a note.",
		positionals: [{ name: "file", type: "string", label: "File", required: true }],
		flags: [],
		executionMode: "buffered",
	},
	{
		id: "neighbors",
		argvPath: ["neighbors"],
		category: "search",
		label: "Neighbors",
		positionals: [{ name: "file", type: "string", label: "File", required: true }],
		flags: [
			{
				flag: "--category",
				type: "enum",
				label: "Category",
				enumValues: ["Up", "Down", "Right", "Left", "In", "Out", "Uncategorized"],
			},
			{ flag: "--direction", type: "enum", label: "Direction", enumValues: ["out", "in", "both"], default: "both" },
		],
		executionMode: "buffered",
		jsonFlag: "--json",
	},
	{
		id: "siblings",
		argvPath: ["siblings"],
		category: "search",
		label: "Siblings",
		description: "Notes sharing at least N Up/parent links.",
		positionals: [{ name: "file", type: "string", label: "File", required: true }],
		flags: [{ flag: "--shared-min", type: "number", label: "Minimum shared links", default: 1 }],
		executionMode: "buffered",
		jsonFlag: "--json",
	},
	{
		id: "distance",
		argvPath: ["distance"],
		category: "search",
		label: "Distance (shortest-path hops)",
		positionals: [
			{ name: "a", type: "string", label: "From file", required: true },
			{ name: "b", type: "string", label: "To file", required: true },
		],
		flags: [
			{ flag: "--max", type: "number", label: "Max hops", default: 6 },
			{ flag: "--include-external", type: "boolean", label: "Include external links" },
		],
		executionMode: "buffered",
		jsonFlag: "--json",
	},
	{
		id: "path",
		argvPath: ["path"],
		category: "search",
		label: "Path (shortest path as file list)",
		positionals: [
			{ name: "a", type: "string", label: "From file", required: true },
			{ name: "b", type: "string", label: "To file", required: true },
		],
		flags: [
			{ flag: "--max", type: "number", label: "Max hops", default: 6 },
			{ flag: "--include-external", type: "boolean", label: "Include external links" },
		],
		executionMode: "buffered",
	},
	{
		id: "find-by-distance",
		argvPath: ["find-by-distance"],
		category: "search",
		label: "Find by distance (BFS neighborhood)",
		positionals: [{ name: "file", type: "string", label: "File", required: true }],
		flags: [
			{ flag: "--max-distance", type: "number", label: "Max distance", default: 2 },
			{ flag: "--file-type", type: "string", label: "File type tag" },
			{ flag: "--include-existing", type: "boolean", label: "Include existing notes" },
			{ flag: "--include-external", type: "boolean", label: "Include external links" },
		],
		executionMode: "buffered",
		jsonFlag: "--json",
	},
	{
		id: "metrics.compute",
		argvPath: ["metrics", "compute"],
		category: "infra",
		label: "Metrics → Compute",
		description: "PageRank, betweenness, clustering coefficient, degree, community.",
		positionals: [],
		flags: [{ flag: "--collection", type: "string", label: "Collection" }],
		executionMode: "streaming",
	},
	{
		id: "metrics.show",
		argvPath: ["metrics", "show"],
		category: "search",
		label: "Metrics → Show",
		positionals: [],
		flags: [
			{ flag: "--collection", type: "string", label: "Collection" },
			{ flag: "--top", type: "number", label: "Top N" },
			{
				flag: "--sort",
				type: "enum",
				label: "Sort by",
				enumValues: ["pagerank", "betweenness", "clustering_coeff", "in_degree", "out_degree", "community"],
			},
			{
				flag: "--filter",
				type: "string",
				label: "Min/max filters",
				description:
					"field=value pairs, e.g. in_degree=50 (maps to the CLI's --min-<field>/--max-<field> flags; UI wiring for this is a follow-up)",
				repeatable: true,
			},
		],
		executionMode: "buffered",
		jsonFlag: "--json",
	},
];

export const qnodeSchema: ToolSchema = { id: "qnode", commands };
