import { CommandNode, ToolSchema } from "../types";

const commands: CommandNode[] = [
	{
		id: "collection",
		argvPath: ["collection"],
		category: "infra",
		label: "Register/inspect vault",
		description: "Run without --path to print the current settings for that collection instead.",
		positionals: [{ name: "name", type: "string", label: "Collection name", required: true }],
		flags: [{ flag: "--path", type: "path", label: "Vault path" }],
		executionMode: "buffered",
	},
	{
		id: "collections",
		argvPath: ["collections"],
		category: "infra",
		label: "List collections",
		positionals: [],
		flags: [{ flag: "--remove", type: "string", label: "Unregister a collection" }],
		executionMode: "buffered",
	},
	{
		id: "index",
		argvPath: ["index"],
		category: "infra",
		label: "Index (extract unresolved wikilinks)",
		positionals: [],
		flags: [
			{ flag: "--collection", type: "string", label: "Collection" },
			{ flag: "--force", type: "boolean", label: "Force full rescan" },
		],
		executionMode: "streaming",
	},
	{
		id: "embed",
		argvPath: ["embed"],
		category: "infra",
		label: "Embed unresolved targets",
		description: "Required before find-similar.",
		positionals: [],
		flags: [
			{ flag: "--collection", type: "string", label: "Collection" },
			{ flag: "--force", type: "boolean", label: "Force re-embed" },
		],
		executionMode: "streaming",
	},
	{
		id: "query",
		argvPath: ["query"],
		category: "search",
		label: "Query",
		positionals: [],
		flags: [
			{
				flag: "--destination",
				type: "string",
				label: "Destination type(s)",
				description: "Comma-separated OR of idea/person/date/file/template/unknown",
			},
			{ flag: "--origin", type: "string", label: "Origin folder prefix" },
			{ flag: "--semantic-type", type: "string", label: "Semantic-type annotation" },
			{ flag: "--min-occurrences", type: "number", label: "Minimum occurrences" },
			{ flag: "--search", type: "string", label: "Text search" },
			{ flag: "--limit", type: "number", label: "Result limit" },
			{
				flag: "--format",
				type: "enum",
				label: "Output format",
				enumValues: ["summary", "detailed", "json"],
				default: "summary",
			},
		],
		executionMode: "buffered",
	},
	{
		id: "find-similar",
		argvPath: ["find-similar"],
		category: "search",
		label: "Find similar / duplicate detection",
		positionals: [{ name: "query", type: "string", label: "Query", required: false }],
		flags: [
			{ flag: "--cluster", type: "boolean", label: "Cluster mode" },
			{ flag: "--top-k", type: "number", label: "Top K", default: 10 },
			{ flag: "--min-score", type: "number", label: "Minimum score", default: 0.5 },
			{ flag: "--threshold", type: "number", label: "Cluster threshold", default: 0.82 },
			{ flag: "--collection", type: "string", label: "Collection" },
		],
		executionMode: "buffered",
	},
	{
		id: "classify",
		argvPath: ["classify"],
		category: "infra",
		label: "Classify low-confidence entries",
		description: "Requires a trained classifier model.",
		positionals: [],
		flags: [
			{ flag: "--collection", type: "string", label: "Collection" },
			{ flag: "--dry-run", type: "boolean", label: "Dry run" },
		],
		executionMode: "streaming",
	},
	{
		id: "classifier.train",
		argvPath: ["classifier", "train"],
		category: "infra",
		label: "Classifier → Train",
		positionals: [
			{ name: "path", type: "path", label: "Examples directory", required: true },
			{ name: "label", type: "string", label: "Label", required: true },
		],
		flags: [
			{ flag: "--append", type: "boolean", label: "Append to existing training data" },
			{ flag: "--output", type: "path", label: "Output model path" },
		],
		executionMode: "streaming",
		destructive: true,
	},
	{
		id: "classifier.retrain",
		argvPath: ["classifier", "retrain"],
		category: "infra",
		label: "Classifier → Retrain",
		description: "Rebuilds the model from all accumulated training files.",
		positionals: [],
		flags: [{ flag: "--output", type: "path", label: "Output model path" }],
		executionMode: "streaming",
		destructive: true,
	},
];

export const qvoidSchema: ToolSchema = { id: "qvoid", commands };
